# Generated by Django 3.1.4 on 2020-12-12 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20201211_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='orders',
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='items.item'),
        ),
    ]
